apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
spec:
  selector:
      matchLabels:
        app: movie-service
  replicas: 1
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
        - name: movie-service
          image: oionis/movie-service
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
